{% set python_min = '3.10' %}
{% set name = "gsffile" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gsffile-{{ version }}.tar.gz
  sha256: bc8005e1da790837efb2d23654d192681326940a72c07a884f66605eda70e3f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24

test:
  imports:
    - gsffile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/angelo-peronio/gsffile
  summary: Read and write Gwyddion Simple Field files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
    - angelo-peronio
