schema_version: 1

context:
  python_min: '3.10'
  name: gsffile
  version: "0.5.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gsffile-${{ version }}.tar.gz
  sha256: 851a20d64cbeda3310d32d2cf7bce28955523dc45f31d7d4e1c292ac32e41469

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.24

tests:
  - python:
      imports:
        - gsffile
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Read and write Gwyddion Simple Field files
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/angelo-peronio/gsffile

extra:
  recipe-maintainers:
    - carlodri
    - angelo-peronio
