schema_version: 1

context:
  python_min: 3.10
  name: gsffile
  version: 0.5.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gsffile-${{ version }}.tar.gz
  sha256: ab5dd83eae4e260757c3189c4e2ad8a55283fcfa54e9512bba5cd4c01927f230

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.24

tests:
  - python:
      imports:
        - gsffile
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Read and write Gwyddion Simple Field files
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/angelo-peronio/gsffile

extra:
  recipe-maintainers:
    - carlodri
    - angelo-peronio
